//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientsManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int ID { get; set; }
        public string INN { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public System.DateTime DateContract { get; set; }
        public string Contacts { get; set; }
    
        public virtual ClientsTypes ClientsTypes { get; set; }
    }
}
